apiVersion: v2
name: diagnosis-app
description: Helm chart for diagnosis-app
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: "ghostbim21"
    email: "ghostbim21@gmail.com"