apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diagnosis-app
spec:
  ingressClassName: traefik
  rules:
  - host: diagnosis-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diagnosis-app
            port:
              number: 80