apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: diagnosis-app-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: diagnosis-service
  endpoints:
    - port: http
      path: /metrics