apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnosis-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: diagnosis-app
  template:
    metadata:
      labels:
        app: diagnosis-app
    spec:
      containers:
        - name: diagnosis-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000